import type {
  AuditStatus,
  CountMap,
  DocGovernance,
  DocGovernanceStatus,
  DocsRegistryEntry,
  DocsRegistry,
  DocStatus,
} from "./types.mts";

import { discoverGovernanceDocumentPaths } from "./documents.mts";
import { collectWatchPathSourcesWithConfig } from "./references.mts";
import { gitDirtyPaths, latestCommitTimestamp, readJson } from "./repo.mts";
import { endOfDayUnix, formatUnixDate } from "./utils.mts";

async function loadDocsRegistry() {
  return readJson<DocsRegistry>("docs/docs-registry.json");
}

function isPathWithinPrefix(targetPath: string, prefix: string) {
  return targetPath === prefix || targetPath.startsWith(`${prefix}/`);
}

function isApiSpecificDocument(docPath: string, watchPaths: string[]) {
  if (isPathWithinPrefix(docPath, "apps/api")) {
    return true;
  }

  if (watchPaths.length === 0) {
    return false;
  }

  const apiScopedPrefixes = ["apps/api", "packages/types", "packages/game-logic"];
  const hasApiWatchPath = watchPaths.some((watchPath) => isPathWithinPrefix(watchPath, "apps/api"));
  const hasOnlyApiScopedWatchPaths = watchPaths.every((watchPath) =>
    apiScopedPrefixes.some((prefix) => isPathWithinPrefix(watchPath, prefix)),
  );

  return hasApiWatchPath && hasOnlyApiScopedWatchPaths;
}

function resolveDocDri(docPath: string, watchPaths: string[], generated: boolean) {
  if (generated) {
    return "모두";
  }

  return isApiSpecificDocument(docPath, watchPaths) ? "박준형" : "모두";
}

function resolveDocKind(docPath: string, entry: DocsRegistryEntry) {
  if (entry.kind) {
    return entry.kind;
  }

  if (docPath === "docs/prd/README.md") {
    return "prd-index";
  }

  if (docPath.startsWith("docs/prd/")) {
    return "product-manual";
  }

  if (docPath === "README.md") {
    return "workspace-guide";
  }

  if (docPath.endsWith("/README.md")) {
    return "readme";
  }

  if (docPath.includes("/plans/")) {
    return "plan";
  }

  if (docPath.includes("prd")) {
    return "prd";
  }

  return "document";
}

export async function collectDocGovernance(): Promise<DocGovernance> {
  const registry = await loadDocsRegistry();
  const docPaths = await discoverGovernanceDocumentPaths(registry);
  const statuses: DocGovernanceStatus[] = [];

  for (const docPath of docPaths) {
    const entry = registry.documents?.[docPath] ?? {};
    const watchSources = entry.generated
      ? { autoWatchPaths: [], manualWatchPaths: [], watchPaths: [] }
      : await collectWatchPathSourcesWithConfig(docPath, {
          ...(entry.ignoreWatchPaths ? { ignoredWatchPaths: entry.ignoreWatchPaths } : {}),
          ...(entry.watchPaths ? { watchPathOverrides: entry.watchPaths } : {}),
        });
    const { autoWatchPaths, manualWatchPaths, watchPaths } = watchSources;
    const lastReviewedAt = entry.lastReviewedAt ?? null;
    const latestWatchedCommit = entry.generated ? null : await latestCommitTimestamp(watchPaths);
    const docDirtyPaths = entry.generated ? [] : await gitDirtyPaths([docPath]);
    const watchedDirtyPaths = entry.generated ? [] : await gitDirtyPaths(watchPaths);

    let status: DocStatus = "manual";
    let reason = "manual review";

    if (entry.generated) {
      status = "generated";
      reason = "generated by docs harness";
    } else if (!lastReviewedAt && watchPaths.length === 0) {
      status = "manual";
      reason = "review date not set and no watch paths detected";
    } else if (!lastReviewedAt) {
      status = "manual";
      reason = "review date not set";
    } else if (watchPaths.length === 0) {
      status = "manual";
      reason = "no watch paths detected";
    } else if (
      latestWatchedCommit &&
      lastReviewedAt &&
      latestWatchedCommit > endOfDayUnix(lastReviewedAt)
    ) {
      status = "stale";
      reason = `watched paths changed on ${formatUnixDate(latestWatchedCommit)} after review date ${lastReviewedAt}`;
    } else {
      status = "current";
      reason = lastReviewedAt ? `reviewed on ${lastReviewedAt}` : "up to date";
    }

    let auditStatus: AuditStatus = status;
    let auditReason = reason;

    if (!entry.generated && watchedDirtyPaths.length > 0) {
      if (docDirtyPaths.length > 0) {
        auditStatus = "in-progress";
        auditReason =
          "watched paths changed and the document is also being updated in the working tree";
      } else {
        auditStatus = "stale-working-tree";
        auditReason = `watched paths changed in working tree: ${watchedDirtyPaths.slice(0, 3).join(", ")}`;
      }
    }

    statuses.push({
      docPath,
      dri: resolveDocDri(docPath, watchPaths, Boolean(entry.generated)),
      kind: resolveDocKind(docPath, entry),
      generated: Boolean(entry.generated),
      lastReviewedAt,
      latestWatchedCommit,
      watchPaths,
      status,
      reason,
      auditStatus,
      auditReason,
      autoWatchPaths,
      watchedDirtyPaths,
      docDirtyPaths,
      manualWatchPaths,
    });
  }

  const counts = statuses.reduce((accumulator, item) => {
    accumulator[item.status] = (accumulator[item.status] ?? 0) + 1;
    return accumulator;
  }, {} as CountMap);

  const auditCounts = statuses.reduce((accumulator, item) => {
    accumulator[item.auditStatus] = (accumulator[item.auditStatus] ?? 0) + 1;
    return accumulator;
  }, {} as CountMap);

  statuses.sort((left, right) => left.docPath.localeCompare(right.docPath));

  return {
    statuses,
    counts,
    auditCounts,
  };
}
